repos:
  # Ruff: lint + autofix (sem formatador do ruff; usaremos Black para formatar)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
        files: "^(services|tests)/.*\\.py$"

  # Black: formatador
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        files: "^(services|tests)/.*\\.py$"

  # Mypy: type-check
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        files: "^(services|tests)/.*\\.py$"
        args: ["--config-file=mypy.ini"]
        # Dependências de tipos/libs necessárias para os imports do projeto
        additional_dependencies:
          - types-requests
          - types-Pillow
          - pydantic>=2.8.0
          - fastapi>=0.115.0
          - types-PyYAML

  # Hooks utilitários
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=1024"]
