line-length = 100
target-version = "py311"

[lint]
# Conjuntos: E/F (pycodestyle/pyflakes), I (isort), UP (pyupgrade), B (flake8-bugbear)
select = ["E", "F", "I", "UP", "B"]
ignore = []

[lint.isort]
known-first-party = ["services"]
combine-as-imports = true
split-on-trailing-comma = true