name: "Oficina do Zé"

features:
  enable_text: true
  enable_vision: true
  enable_ocr: false

limits:
  max_input_tokens: 4096
  max_output_tokens: 1024
  max_images_per_request: 4

models:
  text_model: "gpt-4o-mini"
  vision_model: "gpt-4o"
  ocr_model: "tesseract"

cors:
  origins:
    - "https://painel.oficinadoze.com"
    - "http://localhost:5173"

rate_limit:
  default:
    rpm: 40
    burst: 80
  routes:
    "/v1/ping":
      rpm: 20
      burst: 40
    "/v1/text/analyze":
      rpm: 15
      burst: 30
    "/v1/vision/analyze":
      rpm: 8
      burst: 16
