name: CI (ruff, mypy, pytest)

on:
  push:
    branches: [ "main", "develop" ]
    paths-ignore:
      - "**/*.md"
      - "README.md"
  pull_request:
    branches: [ "main", "develop" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: ".ci/requirements.txt"

      - name: Install deps (CI)
        run: |
          python -m pip install -U pip
          pip install -r .ci/requirements.txt

      - name: Ruff (lint)
        run: |
          ruff --version
          ruff check . --output-format=github

      - name: Mypy (type check)
        run: |
          mypy --version
          mypy services tests

      - name: Pytest (unit tests)
        run: |
          pytest -q
